#!/bin/bash
# Usage: git open

# Retrieve Git Remote
GIT_ENDPOINT=$(git config --get remote.origin.url)

# Build HTTPS GitLab Endpoint
REMOVED_COLON=${GIT_ENDPOINT/://}
ADDED_PROTOCOL=${REMOVED_COLON/git@/https://}
GIT_URL=${ADDED_PROTOCOL/.git/}

# Launch URL in Default Browser
python -mwebbrowser $GIT_URL